version: 2.1
orbs:
  go: circleci/go@1.7.1
  node: circleci/node@5.0.3
jobs:
  configure:
    docker:
      - image: ubuntu:16.04
      - image: node:18.12
      - image: golang:1.19.4
    resource_class: medium
    steps:
      - run: 
          name: Insall Dependices
          command: apt update && apt install git sudo wget curl -y    
      - run: 
          name: Install Node 18
          command: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list    	curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - run: 
          name: Install Yarn
          command: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - run: 
          name: Install Go
          command: wget -c https://golang.google.cn/dl/go1.19.4.linux-amd64.tar.gz && tar -C /usr/local -zxvf go1.19.4.linux-amd64.tar.gz && echo 'export GOROOT=/usr/local/go' >> /etc/profile &&             echo 'export PATH=$PATH:$GOROOT/bin' >> /etc/profile && source /etc/profile
      - run: 
          name: Insall Dependices
          command: apt update && apt install git nodejs sudo wget curl -y
      - run: 
          name: Fetch Code
          command: mkdir /home/runner && cd /home/runner && git clone https://github.com/usememos/memos.git
      - run: 
          name: Build Frontend
          command: cd /home/runner/memos && mkdir /home/runner/frontend-build && cp -rf /home/runner/memos/web/. /home/runner/frontend-build && cd /home/runner/frontend-build && yarn && yarn build
      - run: 
          name: Build Backend
          command: cd /home/runner/memos && mkdir /home/runner/backend-build && cp -rf /home/runner/memos/. /home/runner/backend-build && cp -rf /home/runner/frontend-build/dist/. /home/runner/backend-build/server/dist && cd /home/runner/backend-build && go build -o memos ./bin/server/main.go
      - store_artifacts:
          path: /home/runner/backend-build/memos
workflows:
  configure:
    jobs:
      - configure
